POST  http://127.0.0.1:8080/add_data
Content-Type: application/json

{
  "data1": "Jonny2",
  "data2": "last2"
}

###

POST  http://127.0.0.1:8080/remove_data
Content-Type: application/json

{
  "id": 67
}

###

POST  http://127.0.0.1:8080/update_data
Content-Type: application/json

{
  "id": 3,
  "data1": "Fillll",
  "data2": "1234567"
}

###

GET  http://127.0.0.1:8080/3
Content-Type: application/json


###

GET  http://127.0.0.1:8080/
Content-Type: application/json