POST  http://127.0.0.1:8080/add_data
Content-Type: application/json

{
  "data1": "Tom",
  "data2": "9999"
}

###

POST  http://127.0.0.1:8080/remove_data
Content-Type: application/json

{
  "id": "12ac3f62-9bb4-43c8-b12b-b8e404ef0e5a"
}

###

POST  http://127.0.0.1:8080/update_data
Content-Type: application/json

{
  "id": "0915e53c-74d9-4435-986e-ed6c1239487f",
  "data1": "Fil",
  "data2": "1234567"
}

###