version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - "8080:80"
#      - "80:80"
    depends_on:
      - server

  server:
    image: my_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - database
#    ports:
#      - "8080"

  database: # <= POSTGRES_HOST in postgres connection URL (POSTGRES_HOST=localhost if run not in docker container)
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
