
-- CREATE SCHEMA IF NOT EXISTS base

CREATE TABLE IF NOT EXISTS important_data(
    id SERIAL NOT NULL PRIMARY KEY,
    data1 TEXT,
    data2 VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);